-- MySQL Script generated by MySQL Workbench
-- Mon Mar 17 17:39:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema my_herd_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_herd_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_herd_app` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema profisa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema profisa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `profisa` ;
USE `my_herd_app` ;

-- -----------------------------------------------------
-- Table `my_herd_app`.`profiles_advisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`profiles_advisor` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`profiles_advisor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `profile_picture` VARCHAR(255) NULL DEFAULT NULL,
  `linkedin_url` VARCHAR(45) NULL DEFAULT NULL,
  `instagram_url` VARCHAR(45) NULL DEFAULT NULL,
  `overview` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `profile_completed` TINYINT(1) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `Idx_FK_users` ON `my_herd_app`.`profiles_advisor` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `my_herd_app`.`skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`skills` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `my_herd_app`.`advisor_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`advisor_skills` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`advisor_skills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_profiles_advisor` INT NOT NULL,
  `id_skills` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_advisor_skills_profile`
    FOREIGN KEY (`id_profiles_advisor`)
    REFERENCES `my_herd_app`.`profiles_advisor` (`id`),
  CONSTRAINT `FK_advisor_skills_skills`
    FOREIGN KEY (`id_skills`)
    REFERENCES `my_herd_app`.`skills` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_advisor_skills_profile` ON `my_herd_app`.`advisor_skills` (`id_profiles_advisor` ASC) VISIBLE;

CREATE INDEX `FK_advisor_skills_skills` ON `my_herd_app`.`advisor_skills` (`id_skills` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `my_herd_app`.`cache`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`cache` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`cache` (
  `key` VARCHAR(255) NOT NULL,
  `value` MEDIUMTEXT NOT NULL,
  `expiration` INT NOT NULL,
  PRIMARY KEY (`key`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `my_herd_app`.`cache_locks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`cache_locks` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`cache_locks` (
  `key` VARCHAR(255) NOT NULL,
  `owner` VARCHAR(255) NOT NULL,
  `expiration` INT NOT NULL,
  PRIMARY KEY (`key`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `my_herd_app`.`career_finders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`career_finders` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`career_finders` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `my_herd_app`.`chirps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`chirps` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`chirps` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `my_herd_app`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`courses` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `courses_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `my_herd_app`.`education`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`education` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`education` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Institution_name` VARCHAR(45) NULL DEFAULT NULL,
  `id_courses` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_Courses_Id_course`
    FOREIGN KEY (`id_courses`)
    REFERENCES `my_herd_app`.`courses` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_couses` ON `my_herd_app`.`education` (`id_courses` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `my_herd_app`.`failed_jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`failed_jobs` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`failed_jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `failed_jobs_uuid_unique` ON `my_herd_app`.`failed_jobs` (`uuid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `my_herd_app`.`profiles_finder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`profiles_finder` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`profiles_finder` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `profile_picture` VARCHAR(45) NULL DEFAULT NULL,
  `linkedin_url` VARCHAR(45) NULL DEFAULT NULL,
  `instagram_url` VARCHAR(45) NULL DEFAULT NULL,
  `overview` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `profile_completed` TINYINT(1) NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_profile_user2`
    FOREIGN KEY (`user_id`)
    REFERENCES `profisa`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_profile_user_idx` ON `my_herd_app`.`profiles_finder` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `my_herd_app`.`finder_interest_areas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`finder_interest_areas` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`finder_interest_areas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_courses` INT NULL DEFAULT NULL,
  `id_profiles_finder` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_courses_finder_areas`
    FOREIGN KEY (`id_courses`)
    REFERENCES `my_herd_app`.`courses` (`id`),
  CONSTRAINT `FK_finder_areas`
    FOREIGN KEY (`id_profiles_finder`)
    REFERENCES `my_herd_app`.`profiles_finder` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_courses_idx` ON `my_herd_app`.`finder_interest_areas` (`id_courses` ASC) VISIBLE;

CREATE INDEX `FK_finder_idx` ON `my_herd_app`.`finder_interest_areas` (`id_profiles_finder` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `my_herd_app`.`finder_skills_interests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`finder_skills_interests` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`finder_skills_interests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_profiles_finder` INT NOT NULL,
  `id_skills` INT NOT NULL,
  `importance_level` INT NOT NULL DEFAULT '3',
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_finder_skills_profile`
    FOREIGN KEY (`id_profiles_finder`)
    REFERENCES `my_herd_app`.`profiles_finder` (`id`),
  CONSTRAINT `FK_finder_skills_skills`
    FOREIGN KEY (`id_skills`)
    REFERENCES `my_herd_app`.`skills` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_finder_skills_profile` ON `my_herd_app`.`finder_skills_interests` (`id_profiles_finder` ASC) VISIBLE;

CREATE INDEX `FK_finder_skills_skills` ON `my_herd_app`.`finder_skills_interests` (`id_skills` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `my_herd_app`.`job_batches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`job_batches` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`job_batches` (
  `id` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `total_jobs` INT NOT NULL,
  `pending_jobs` INT NOT NULL,
  `failed_jobs` INT NOT NULL,
  `failed_job_ids` LONGTEXT NOT NULL,
  `options` MEDIUMTEXT NULL DEFAULT NULL,
  `cancelled_at` INT NULL DEFAULT NULL,
  `created_at` INT NOT NULL,
  `finished_at` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `my_herd_app`.`jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`jobs` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `queue` VARCHAR(255) NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `attempts` TINYINT UNSIGNED NOT NULL,
  `reserved_at` INT UNSIGNED NULL DEFAULT NULL,
  `available_at` INT UNSIGNED NOT NULL,
  `created_at` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `jobs_queue_index` ON `my_herd_app`.`jobs` (`queue` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `my_herd_app`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`logs` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `action` VARCHAR(255) NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `my_herd_app`.`meeting_requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`meeting_requests` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`meeting_requests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_profiles_finder` INT NOT NULL,
  `id_profiles_advisor` INT NOT NULL,
  `status` ENUM('pending', 'accepted', 'declined') NOT NULL DEFAULT 'pending',
  `finder_message` TEXT NULL DEFAULT NULL,
  `advisor_response` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_meeting_advisor`
    FOREIGN KEY (`id_profiles_advisor`)
    REFERENCES `my_herd_app`.`profiles_advisor` (`id`),
  CONSTRAINT `FK_meeting_finder`
    FOREIGN KEY (`id_profiles_finder`)
    REFERENCES `my_herd_app`.`profiles_finder` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_meeting_finder` ON `my_herd_app`.`meeting_requests` (`id_profiles_finder` ASC) VISIBLE;

CREATE INDEX `FK_meeting_advisor` ON `my_herd_app`.`meeting_requests` (`id_profiles_advisor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `my_herd_app`.`migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`migrations` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`migrations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `my_herd_app`.`password_reset_tokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`password_reset_tokens` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`password_reset_tokens` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `my_herd_app`.`profile_education`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`profile_education` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`profile_education` (
  `id_profiles_education` INT NOT NULL AUTO_INCREMENT,
  `id_profiles_advisor` INT NULL DEFAULT NULL,
  `id_profiles_finder` INT NULL DEFAULT NULL,
  `id_courses` INT NULL DEFAULT NULL,
  `institution_name` VARCHAR(45) NULL DEFAULT NULL,
  `certification` VARCHAR(45) NULL DEFAULT NULL,
  `dt_start` DATE NULL DEFAULT NULL,
  `dt_end` DATE NULL DEFAULT NULL,
  `comments` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL COMMENT '		',
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_profiles_education`),
  CONSTRAINT `FK_courses`
    FOREIGN KEY (`id_courses`)
    REFERENCES `my_herd_app`.`courses` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 216
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_profile_advisor_idx` ON `my_herd_app`.`profile_education` (`id_profiles_advisor` ASC) VISIBLE;

CREATE INDEX `FK_profiles_finder_idx` ON `my_herd_app`.`profile_education` (`id_profiles_finder` ASC) VISIBLE;

CREATE INDEX `FK_courses` ON `my_herd_app`.`profile_education` (`id_courses` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `my_herd_app`.`requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`requests` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`requests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` ENUM('pending', 'approved', 'declined') NULL DEFAULT 'pending',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `id_profiles_advisor` INT NULL DEFAULT NULL,
  `id_profiles_finder` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FK_requests_advisor_idx` ON `my_herd_app`.`requests` (`id_profiles_advisor` ASC) VISIBLE;

CREATE INDEX `FK_requests_finder_idx` ON `my_herd_app`.`requests` (`id_profiles_finder` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `my_herd_app`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`sessions` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`sessions` (
  `id` VARCHAR(255) NOT NULL,
  `user_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` TEXT NULL DEFAULT NULL,
  `payload` LONGTEXT NOT NULL,
  `last_activity` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE INDEX `sessions_user_id_index` ON `my_herd_app`.`sessions` (`user_id` ASC) VISIBLE;

CREATE INDEX `sessions_last_activity_index` ON `my_herd_app`.`sessions` (`last_activity` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `my_herd_app`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_herd_app`.`users` ;

CREATE TABLE IF NOT EXISTS `my_herd_app`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE UNIQUE INDEX `users_email_unique` ON `my_herd_app`.`users` (`email` ASC) VISIBLE;

USE `profisa` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
